# Generated by generate-wrapper-unit-tests.py; do not edit.
set(P101_FAULT_SHARD_TESTS
    test_fault_wrappers_aio
    test_fault_wrappers_fcntl
    test_fault_wrappers_poll
    test_fault_wrappers_stdio
    test_fault_wrappers_sys_select
    test_fault_wrappers_sys_uio
    test_fault_wrappers_unistd
)
